// react-app/src/Component/Reactivity.tsx
import { useState } from "react";

let index = 0;

export const Reactivity = () => {

  console.log(index++);

  const [count, setCount] = useState(0);

  return (
    <div>
      <h3>Reactivity</h3>
      <p>Value of count: {count}</p>
      <button onClick={() => setCount(count + 1)}>Click to increase count</button>
    </div>
  );
}

// angular-app/src/app/reactivity/reactivity.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-reactivity',
  templateUrl: './reactivity.component.html',
  styleUrls: ['./reactivity.component.css']
})
export class ReactivityComponent {


  public count = 0;

  public increaseCount() {
    console.log(this.count);
    this.count++;
  }

}

<div>
  <h3>Reactivity</h3>
  <p>Value of count: {{count}}</p>
  <button (click)="increaseCount()">Click to increase count</button>
</div>
