// angular-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angular-app';

  public count = 0;

  public increaseCount() {
    console.log(this.count);
    this.count++;
  }
}

<div class="App">
  <h1>Hello from Angular 👋 !</h1>
  <div>
    <p>Value of count: {{count}}</p>
    <button (click)="increaseCount()">Click to increase count</button>
  </div>
</div>

// react-app/src/App.tsx
import { useState } from 'react';
import './App.css';

function App() {

  const [count, setCount] = useState(0);

  return (
    <div className="App">
      <h1>Hello from React 👋 !</h1>
      <div>
        <p>Value of count: {count}</p>
        <button onClick={() => setCount(count + 1)}>Click to increase count</button>
      </div>
    </div>
  );
}

export default App;
